# -*- coding: utf-8 -*-
# Generated by Django 2.2.5 on 2019-09-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('monetary', 'Money based coupon'), ('percentage', 'Percentage discount'), ('virtual_currency', 'Virtual currency'), ('time', 'Time based coupon')], max_length=20, verbose_name='Type'),
        ),
    ]
